# Generated by Django 3.1.2 on 2020-10-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0004_dealer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dealer',
            new_name='Deal',
        ),
    ]
