# Generated by Django 3.1.2 on 2020-10-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='File',
        ),
    ]
