# Generated by Django 3.1.2 on 2020-10-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0002_auto_20201003_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='datafile',
            field=models.FileField(upload_to=''),
        ),
    ]
