# Generated by Django 3.1.2 on 2020-10-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0003_auto_20201003_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('item', models.CharField(blank=True, max_length=255)),
                ('total', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
