# Generated by Django 3.1.2 on 2020-10-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0005_auto_20201004_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='item',
            field=models.CharField(max_length=255),
        ),
    ]
